#!/bin/bash

sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

g++ -o game src/Game.cpp src/Main.cpp src/entities/Obstacle.cpp src/entities/ObstacleManager.cpp src/entities/Player.cpp -lSDL2 -lSDL2_image -lSDL2_ttf
